from typing import Any

from pydantic import BaseModel, Field


class AnalysisPlan(BaseModel):
    """
    Execution plan generated by the Planner.
    """

    intent: str
    target_signals: list[str] = Field(default_factory=list)
    time_window: str | None = None
    analysis: list[str] = Field(default_factory=list)
    execution_steps: list[str] = Field(default_factory=list)
    visualization: str | None = None
    reason: str


class ToolResult(BaseModel):
    """
    Standard output returned by every analytical tool.
    """

    tool_name: str
    status: str
    result: dict[str, Any]
    explanation: str | None = None
    chart: Any | None = None


class GuardrailResult(BaseModel):
    """
    Output of the Guardrail layer.
    """

    allowed: bool
    reason: str
    message: str